#!/usr/bin/env python3
import wx, send

length = 300 
width  = 300
title = 'TEST'

btn1  = 'btn1'
btn2  = 'btn2'
btn3  = 'END'
btn4  = 'SEND'

class Frame(wx.Frame):
	
	def __init__(self):
		#----------------|不太用動到   |標題 | 視窗大小    				  
		wx.Frame.__init__(self,None,-1, title , size=(length, width))
		
		panel = wx.Panel(self,-1)
		
		wx.StaticText(panel, -1, "STATE:", pos=(10,15))
		
		#有幾個按鈕
		self.posCtrl  = wx.TextCtrl(panel,-1,"0000",pos=(60,10))
		self.btn1  = wx.Button(panel,-1,label=btn1, pos=(50,50),size=(50,30))
		self.btn2  = wx.Button(panel,-1,label=btn2, pos=(100,50),size=(50,30))
		self.btn3  = wx.Button(panel,-1,label=btn3, pos=(150,50),size=(50,30))
		self.btn4  = wx.Button(panel,-1,label=btn4, pos=(200,50),size=(50,30))

		#綁定顯示板功能
		panel.Bind(wx.EVT_MOTION,self.Move)
		
		#綁定各個按鈕功能
		#			功能類型   |	功能來源	|按鈕識別
		self.Bind(wx.EVT_BUTTON, self.func_1, self.btn1)
		self.Bind(wx.EVT_BUTTON, self.func_2, self.btn2)
		self.Bind(wx.EVT_BUTTON, self.func_3, self.btn3)
		self.Bind(wx.EVT_BUTTON, self.func_4, self.btn4)
		
	def Move(self, event):
		pos = event.GetPosition()
		self.posCtrl.SetValue("%s, %s" % (pos.x, pos.y))

	def func_1(self, event):
		self.posCtrl.SetValue("Button 1")
	
	def func_2(self, event):
		self.posCtrl.SetValue("Button 2")
		
	def func_3(self, event):
		self.Destroy()

	def func_4(self, event):
		send.send_it()		
		
		
		
if __name__ == '__main__':
	app   = wx.App()
	frame = Frame()
	frame.Show()
	app.MainLoop()
