#!/usr/bin/python3
import os, smtplib, ftplib, datetime, time, pathlib, re, requests, sys
from ftplib import FTP

data_path = '/home/kk/Desktop/DATA/'

# 依次序為[主機IP,使用者帳號,使用者密碼,FTP伺服器檔案路徑(FTP須先建立資料夾)]
win_ip  = '140.116.89.125'
win_usr = 'azes'
win_pwd = 'azes00'
win_cwd = '/azes'

def win_ftp(ip, usr, pwd, cwd):
    ftp = FTP(ftp_ip)
    ftp.login(ftp_usr, ftp_pwd)

    for file in ftp.nlst(ftp_cwd):
        size = ftp.size(ftp_cwd +'/'+file)/(1024*1024)
        print(file, ' ', size)

    ftp.quit()
    
    
win_ftp(win_ip, win_usr, win_pwd, win_cwd)

