#!/usr/bin/env python3
import os, time, datetime, shutil

# path of log
path_0 = r'C:\Users\RSLab\Desktop\777\\'

# source path
path_1 = r'C:\Users\RSLab\Desktop\777\1\\'

# destination path
path_2 = r'C:\Users\RSLab\Desktop\777\2\\'

for file in os.listdir(path_1):
    file_time = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    shutil.copyfile(path_1+file, path_2+file_time)
    #os.rename(path_1+file, path_2+file_time)
    time.sleep(1)
    with open(path_0 + 'rename_log.txt','a') as log:
        log.write(file + ' -> ' + file_time + '\n')
    print(file + ' -> ' + file_time)
